language: python
python:
- '3.6'
sudo: required
services:
- docker
branches:
  only:
  - develop
before_install:
- docker version
install:
- docker pull kbase/kb-sdk
- docker run kbase/kb-sdk genscript > $HOME/bin/kb-sdk
- chmod 755 $HOME/bin/kb-sdk
- export PATH=$PATH:$HOME/bin/kb-sdk
- kb-sdk sdkbase
- kb-sdk test || true
- make build-test-script
- sed -i "s/test_token=/test_token=$TEST_TOKEN/" test_local/test.cfg
- sed -i "s/appdev./ci./" test_local/test.cfg
script:
- kb-sdk test
after_success:
- cp test_local/workdir/.coverage .
- sudo mkdir -p /kb/module/lib/
- sudo cp -R test_local/workdir/kb/module/lib/kb_tophat2 /kb/module/lib/
- coverage report -m
- coveralls
env:
  global:
    secure: SGjFJduSVfTKWXnW7J+NuLNqXKxwecKIAPmEkjE2/kRMCrPYmC/f+KYsv5lpmy+zMh2pbF101cYL1ILVnFcTAOg8rdSW6keA8HNCNK+GpLO61IidEhUVLSLQirCHTbOAQTRjIbetf6J8y64cWfPqFp+tdjlfVrR5GfyauZTgf+WEttGBRgt3q64FUgdha5OsrVYsKgg/AT/57gUeZIDipZNy+PJpC3ucwsUnRlA/OcTVVYjNJiCYEzOJ7Kdq7NbDjZkrWTstFAuAleMQaft3S3H3n0eeAt6XMRucVMOp7KRjOjgOMKd6HKos98uLFOQXKU/jbYpm7cdGnpVTA1UVTFF3NeTegKWdIZZJbkGBsHHpzlkrY3uZCMNXpD47cowmPw5kmqJqEj2FdRLA2BppiI1W6rsk+sKhp58xXViiQYCB04rJA4kyC70F898TA0Nlmeif94uvubOkQrHVZYkSP9/9+VCRGV7C8vq1ax4fUNPzhnS8SJK9Na+Hn+Z+A8pKcns6iP6vt8ThQp3N+NzhXCkilCJiZN5HwUhqX1h1T5JzJy4oIvMtC91RWMfVUiSsSeIUrBmF4o9OC8/TNVTatwCLwNSX+zCG+1w/rFvFf+p7NlaMmcAvLvxHm4D/3OOcFGTk9312acdHMuv1qkmhSmu/PjYpXwbSWrYyFMZS2s4=
    secure: vWI/tfTGt6Mha3sEQE5vrSX9DQI6p6XftYvry0EGEFfJaTG29WG1wq7pgJidB6llm93tN4s1OemlsMwPbfmZ6XmnXkITLQxuiw4hsS+cQIQkh6NyGfnZ1tBcxK5Ro7ONj/H3XeKBLYW7O10dAH+jDb7oLoi2bD6p8DGHIypMWrYp5p8rrD2wa/Vb1rzQ6R3v3p4UTygLOeBc7ORR+TDc1XSfkuc/Cv2rF7wFlHP0Nn5us9Az/IzgqkItPoRIdwxupfFnjzX5UeRV2mHrflZ72SBOVVr8g6A022r9X1H+1aGvpu22cm5tUkBl/FpuJmAfAliTE64bdQZTTj1fIXp8tDNOxALHuUHpoGFd8OPTa0iBudyF2wSsEkk/GeAJ1ypVLSw3QQ1OxfSr65fpXcRJIsSEuU+sEhZ7zsKY4uJd+sk83Ql6obnY9T2G7NrNQJLO7TN4/XnBmr2Mr4w7dTu4BFwtsBGawVxlfhj/y6Id5TSmL0OLdyH603SsZZfEmj6KQfjzDu7N+Su/m7ayK8w60ZeVKEpjCrtxb3pe5cpDfl/klsYapUawOTS67D86fAtSqeOGpPMrPRA6rvZL52b0jZY0JlKRbpEFgyNoCxm2Kt8DlyioIbvD6U9ZgGaK7aao3huMcT/8fqI78heAvfQwyDsjuEUHGKKgfFn/B8AkZgI=
